### ISSUE TITLE
ZF2 Support

### ISSUE THREAD

**Issue by n0v3xx** [milqmedia/MQRedisSessionStorage#2]
Hi can you add ZF2 support? Or can you make a ZF2 release?

With the newest version from this module i get
"Catchable fatal error: Argument 1 passed to MQRedisSessionStorage\Factory\RedisStorageFactory::__invoke() must be an instance of Interop\Container\ContainerInterface, instance of Zend\ServiceManager\ServiceManager given, called in /var/www/application/vendor/milqmedia/mq-redis-session/src/Factory/RedisStorageFactory.php on line 34 and defined in /var/www/application/vendor/milqmedia/mq-redis-session/src/Factory/RedisStorageFactory.php on line 21"

Thanks

I use ZF2. (2.5)

**Comment by n0v3xx** [comment]
I found the problem and make a pull request
#3

**Comment by yo-han** [comment]
Your fix will not work in ZF3. Made a new [release](https://github.com/milqmedia/MQRedisSessionStorage/releases/tag/0.9) specifically for ZF2.
